Kod parçamıza dahil ettiğimiz çeşitli kütüphane nesneleri:
1-)Verilerle daha iyi çalışabilmek için pandas kütüphanesini kodumuza dahil ediyoruz
2-)Lineer Regrasyon yapmak istediğimizden dolayı sklearn.linear_model kütüphanesinden
LinearRegression nesnesini kodumuza dahil ediyoruz.
3-)Verimizi eğitim ve test bölümlerine rastgele bir biçimde parçalayabilmek için
sklearn.model_selection kütüphanesinden train_test_split nesnesini kodumuza dahil ediyoruz. 
4-)Yaptığımız algoritmanın ne kadar doğru sonuçlar üretebildiğini anlayabilmek içinse 
sklearn.metrics kütüphanesinden mean_squared_error nesnesini kodumuza dahil ediyoruz.
5-)mse erro hesabını yaptıktan sonra bir rmse hesabını yapabilmek için numpy kütüphanesinden
sqrt nesnesini kodumuza dahil ediyoruz.

In [39]:
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from numpy import sqrt

Burada verileri pandas sayesinde okuyarak df adında bir değişkene kaydediyoruz.
Daha sonrasında verilerimiz işlerken NULL hatası almamak için
veri setimizde boş bırakılmış özelliklere sahip olan satırları
veri setimizden df.dropna() ile çıkarıyoruz.
lineer regrasyon fonksiyonumuzu model olarak bir değişkene kaydediyoruz.
Aşağıda veri setimizin güncel halini görebilirsiniz

In [40]:
df = pd.read_csv('car_prices.csv')
df = df.dropna()
model = LinearRegression()
df.head()

,year,make,model,trim,body,transmission,vin,state,condition,odometer,color,interior,seller,mmr,sellingprice,saledate
0,2015,Kia,Sorento,LX,SUV,automatic,5xyktca69fg566472,ca,5.0,16639.0,white,black,kia motors america inc,20500.0,21500.0,Tue Dec 16 2014 12:30:00 GMT-0800 (PST)
1,2015,Kia,Sorento,LX,SUV,automatic,5xyktca69fg561319,ca,5.0,9393.0,white,beige,kia motors america inc,20800.0,21500.0,Tue Dec 16 2014 12:30:00 GMT-0800 (PST)
2,2014,BMW,3 Series,328i SULEV,Sedan,automatic,wba3c1c51ek116351,ca,45.0,1331.0,gray,black,financial services remarketing (lease),31900.0,30000.0,Thu Jan 15 2015 04:30:00 GMT-0800 (PST)
3,2015,Volvo,S60,T5,Sedan,automatic,yv1612tb4f1310987,ca,41.0,14282.0,white,black,volvo na rep/world omni,27500.0,27750.0,Thu Jan 29 2015 04:30:00 GMT-0800 (PST)
4,2014,BMW,6 Series Gran Coupe,650i,Sedan,automatic,wba6b2c57ed129731,ca,43.0,2641.0,gray,black,financial services remarketing (lease),66000.0,67000.0,Thu Dec 18 2014 12:30:00 GMT-0800 (PST)

Makinemizi lineer regrasyon kullanarak eğitebilmek için  kullanacağımız bağımsız değişkenlerimizi seçiyoruz.
Bizler burada araç fiyatlarına yani bağımlı değişkenimize etkide bulunabilecek özellikler olarak
year ve odometer özelliklerini bağımsız değişkenlerimiz olarak seçtik.Diğer aracın markası, otomatik vitesinin olup olmaması
gibi nicel olmayıp nitel olan verileri tam olarak nasıl yorumlayabileceğimi tam kestiremediğimden dolayı yukarıda da bashettiğim
gibi year ve odometer özelliklerini bağımsız değişkenlerimiz olarak seçtim.

In [41]:
X = df[["year", "odometer"]]

y = df['sellingprice']
pd.DataFrame(y.head())

   sellingprice
0       21500.0
1       21500.0
2       30000.0
3       27750.0
4       67000.0

In [42]:
pd.DataFrame(X.head())

   year  odometer
0  2015   16639.0
1  2015    9393.0
2  2014    1331.0
3  2015   14282.0
4  2014    2641.0

Verilerimizi makinenin etiketli öğrenimine tabii tutabilmek için verilerimizi train ve test
olarak iki farklı gruba ayırdık.Random_state parametresini 11 sabitleyerek de kodumuzu her
çalıştırdığımız vakit bizlere aynı random dağıtılmış train ve test verilerini vermesini sağladık.
test_size parametresi ise test verileriyle eğitim verilerinin birbirine olan oranının istediğimiz 
sayıda olmasını sağlar.

In [43]:
X_train,X_test,y_train,y_test = train_test_split(X, y,random_state=11,test_size=0.2)

In [44]:
pd.DataFrame(y_train)

        sellingprice
524854       21800.0
344968       13000.0
30237          900.0
254556         800.0
174609       13400.0
...              ...
426025       14300.0
247187       16500.0
337932       35500.0
355185        8800.0
477498       20600.0

[377860 rows x 1 columns]

In [45]:
pd.DataFrame(y_test)

        sellingprice
267885       10600.0
500498       22900.0
494179       47400.0
110661       15900.0
444221       18800.0
...              ...
31683        14300.0
215944       13600.0
165811         500.0
456168        5700.0
439889       34900.0

[94465 rows x 1 columns]

In [46]:
pd.DataFrame(X_test)

        year  odometer
267885  2012   54674.0
500498  2014   39785.0
494179  2015   12599.0
110661  2013   16353.0
444221  2013   31453.0
...      ...       ...
31683   2013   29668.0
215944  2014   14094.0
165811  2007       1.0
456168  2005  149578.0
439889  2008   68481.0

[94465 rows x 2 columns]

Modeliminiz kendisini lineer regrasyon algoritmasıyla eğitebilmesi için emir verdik.

In [47]:
model.fit(X_train,y_train)

LinearRegression()

Burada modelimizin tahminlerde bulunmasını istedik ve daha sonrasında 
modelimizin yaptığı tahminlerle asıl değerleri çıplak gözle karşılaştırmak
amacıyla ekrana bu ikili değerleri yazdırdık

In [48]:
predictions = model.predict(X_test)

In [49]:
comparison = pd.DataFrame({"Actual Values":y_test, "Predictions":predictions})
comparison.head()

        Actual Values   Predictions
267885        10600.0  15883.499047
500498        22900.0  18426.754762
494179        47400.0  20880.158917
110661        15900.0  19003.472564
444221        18800.0  18099.548238

In [50]:
comparison.tail()

        Actual Values   Predictions
31683         14300.0  18206.402868
215944        13600.0  19964.683230
165811          500.0  15026.457632
456168         5700.0   4420.436378
439889        34900.0  11753.052212

Burada ise az önce yapmış olduğumuzuz karşılaştırmanın daha net bir şekilde yapılabilmesi için
performans değerlendirme metriklerinden bazıları olan mse ve rmse'ı kullandık.
Sonucumuz ne kadar 0'a yakın olursa modelimiz tahmin konusunda bir o kadar iyi olacaktır.

In [51]:
rmse = sqrt(mean_squared_error(y_test,predictions))
print(rmse)

7626.45401182546

In [52]:
pd.DataFrame(df[["year","odometer","sellingprice"]])

        year  odometer  sellingprice
0       2015   16639.0       21500.0
1       2015    9393.0       21500.0
2       2014    1331.0       30000.0
3       2015   14282.0       27750.0
4       2014    2641.0       67000.0
...      ...       ...           ...
558831  2011   66403.0       22800.0
558833  2012   54393.0       30800.0
558834  2012   50561.0       34000.0
558835  2015   16658.0       11100.0
558836  2014   15008.0       26700.0

[472325 rows x 3 columns]

Burada ise selling price yani bağımlı değişkenimize bağımsız değişkenlerimizin nasıl ve hangi oranda 
etkilerde bulunduğunu anlayabilmek için korelasyon hesabı yaptık.
Beklediğimiz gibi ikinci el araba satışlarında aracın kilometresinin araç fiyatlarıyla ters bir ilişkide 
olduğunu gözlemeleyebildik

In [53]:
correlations = df[["year","odometer","sellingprice"]].corr()
sale_price_correlations=correlations["sellingprice"]
pd.DataFrame(sale_price_correlations)

              sellingprice
year              0.578933
odometer         -0.577397
sellingprice      1.000000